/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    services: Service;
    testimonials: Testimonial;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'clinic-info': ClinicInfo;
    menu: Menu;
  };
  globalsSelect: {
    'clinic-info': ClinicInfoSelect<false> | ClinicInfoSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  content?:
    | (
        | {
            /**
             * Small pill text above the heading, e.g. "Locally owned · Affordable care"
             */
            badge?: string | null;
            /**
             * Wrap text in {{double braces}} to apply the gradient style.
             */
            title: string;
            subtitle?: string | null;
            heroImage?: (string | null) | Media;
            /**
             * Small badge floating over the hero image, e.g. "Walk-ins Welcome"
             */
            floatingBadge?: string | null;
            /**
             * Floating badge on the hero image showing a starting price.
             */
            showPriceBadge?: boolean | null;
            priceBadgeLabel?: string | null;
            priceBadgePrice?: string | null;
            /**
             * e.g. "500+ happy pet families"
             */
            trustSignalText?: string | null;
            blockSettings?: {
              /**
               * Optional ID for linking directly to this block (e.g. "pricing" creates #pricing)
               */
              anchorId?: string | null;
              spacingTop?: ('0' | '8' | '16' | '24' | '32') | null;
              spacingBottom?: ('0' | '8' | '16' | '24' | '32') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Optionally hide specific services from the marquee
             */
            excludeServices?: (string | Service)[] | null;
            blockSettings?: {
              /**
               * Optional ID for linking directly to this block (e.g. "pricing" creates #pricing)
               */
              anchorId?: string | null;
              spacingTop?: ('0' | '8' | '16' | '24' | '32') | null;
              spacingBottom?: ('0' | '8' | '16' | '24' | '32') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'service-marquee';
          }
        | {
            /**
             * Small text above heading, e.g. "What We Offer"
             */
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            services?: (string | Service)[] | null;
            showCtaCard?: boolean | null;
            ctaHeading?: string | null;
            ctaDescription?: string | null;
            ctaButtonLabel?: string | null;
            ctaButtonLink?: string | null;
            blockSettings?: {
              /**
               * Optional ID for linking directly to this block (e.g. "pricing" creates #pricing)
               */
              anchorId?: string | null;
              spacingTop?: ('0' | '8' | '16' | '24' | '32') | null;
              spacingBottom?: ('0' | '8' | '16' | '24' | '32') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            /**
             * Small text above heading, e.g. "Our Story"
             */
            eyebrow?: string | null;
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            images?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  /**
                   * e.g. "8+", "5k+", "40%"
                   */
                  value: string;
                  /**
                   * e.g. "Years serving our community"
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            blockSettings?: {
              /**
               * Optional ID for linking directly to this block (e.g. "pricing" creates #pricing)
               */
              anchorId?: string | null;
              spacingTop?: ('0' | '8' | '16' | '24' | '32') | null;
              spacingBottom?: ('0' | '8' | '16' | '24' | '32') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            /**
             * Small text above heading, e.g. "Transparent Pricing"
             */
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            /**
             * Each item is one row in the pricing table. Pick a service and optionally a specific tier.
             */
            pricingItems?:
              | {
                  service: string | Service;
                  tierLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            blockSettings?: {
              /**
               * Optional ID for linking directly to this block (e.g. "pricing" creates #pricing)
               */
              anchorId?: string | null;
              spacingTop?: ('0' | '8' | '16' | '24' | '32') | null;
              spacingBottom?: ('0' | '8' | '16' | '24' | '32') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            /**
             * Small text above heading, e.g. "Kind Words"
             */
            eyebrow?: string | null;
            heading?: string | null;
            testimonials?: (string | Testimonial)[] | null;
            blockSettings?: {
              /**
               * Optional ID for linking directly to this block (e.g. "pricing" creates #pricing)
               */
              anchorId?: string | null;
              spacingTop?: ('0' | '8' | '16' | '24' | '32') | null;
              spacingBottom?: ('0' | '8' | '16' | '24' | '32') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            description?: string | null;
            /**
             * Display social media icons from Clinic Info below the buttons
             */
            showSocialIcons?: boolean | null;
            buttons?:
              | {
                  label: string;
                  link: string;
                  variant?: ('default' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            blockSettings?: {
              /**
               * Optional ID for linking directly to this block (e.g. "pricing" creates #pricing)
               */
              anchorId?: string | null;
              spacingTop?: ('0' | '8' | '16' | '24' | '32') | null;
              spacingBottom?: ('0' | '8' | '16' | '24' | '32') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * Choose a visual style for this promotion
             */
            variant: 'banner' | 'card' | 'minimal';
            /**
             * Small label text, e.g. "Grand Opening Special" or "Limited Time"
             */
            badge?: string | null;
            heading: string;
            description?: string | null;
            /**
             * The promotional price to highlight, e.g. "$18"
             */
            price: string;
            /**
             * Text below the price, e.g. "per vaccine"
             */
            priceLabel?: string | null;
            /**
             * Crossed-out comparison price, e.g. "$35+"
             */
            originalPrice?: string | null;
            /**
             * Links to the booking URL from Clinic Info
             */
            ctaLabel?: string | null;
            /**
             * Small text at the bottom, e.g. "No appointment needed — walk-ins welcome"
             */
            footnote?: string | null;
            blockSettings?: {
              /**
               * Optional ID for linking directly to this block (e.g. "pricing" creates #pricing)
               */
              anchorId?: string | null;
              spacingTop?: ('0' | '8' | '16' | '24' | '32') | null;
              spacingBottom?: ('0' | '8' | '16' | '24' | '32') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'promotion';
          }
        | {
            /**
             * Small text above heading, e.g. "Our Location"
             */
            eyebrow?: string | null;
            /**
             * Wrap text in {{double braces}} to apply the gradient style.
             */
            heading?: string | null;
            description?: string | null;
            /**
             * Optional badge text, e.g. "Grand Opening May 2026". Leave blank to hide.
             */
            grandOpeningLabel?: string | null;
            blockSettings?: {
              /**
               * Optional ID for linking directly to this block (e.g. "pricing" creates #pricing)
               */
              anchorId?: string | null;
              spacingTop?: ('0' | '8' | '16' | '24' | '32') | null;
              spacingBottom?: ('0' | '8' | '16' | '24' | '32') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'location';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  _order?: string | null;
  title: string;
  description?: string | null;
  /**
   * Detailed description shown on the service detail page
   */
  longDescription?: string | null;
  icon?: ('heart' | 'syringe' | 'smile' | 'scissors' | 'monitor' | 'chip') | null;
  /**
   * Bullet points shown on the service detail page
   */
  features?:
    | {
        feature: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default price in dollars (whole number, no $ sign). Used when no price tiers are set.
   */
  startingPrice?: number | null;
  /**
   * Average competitor price in dollars (whole number, no $ sign). e.g. 60, 250
   */
  competitorPrice?: number | null;
  /**
   * Optional per-animal or per-size pricing. When tiers exist, they display instead of the single starting price.
   */
  priceTiers?:
    | {
        /**
         * e.g. Dogs, Cats, Small Dogs, Large Dogs
         */
        label: string;
        /**
         * Price in dollars (whole number, no $ sign)
         */
        price: number;
        /**
         * Competitor price for this tier
         */
        competitorPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  quote: string;
  /**
   * e.g. "Maria R."
   */
  authorName: string;
  /**
   * e.g. "Dog mom to Biscuit"
   */
  authorDescription?: string | null;
  /**
   * e.g. "MR" (displayed in avatar circle)
   */
  authorInitials?: string | null;
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  publishedAt?: string | null;
  featuredImage?: (string | null) | Media;
  excerpt?: string | null;
  authors?: (string | User)[] | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              heroImage?: T;
              floatingBadge?: T;
              showPriceBadge?: T;
              priceBadgeLabel?: T;
              priceBadgePrice?: T;
              trustSignalText?: T;
              blockSettings?:
                | T
                | {
                    anchorId?: T;
                    spacingTop?: T;
                    spacingBottom?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'service-marquee'?:
          | T
          | {
              excludeServices?: T;
              blockSettings?:
                | T
                | {
                    anchorId?: T;
                    spacingTop?: T;
                    spacingBottom?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              services?: T;
              showCtaCard?: T;
              ctaHeading?: T;
              ctaDescription?: T;
              ctaButtonLabel?: T;
              ctaButtonLink?: T;
              blockSettings?:
                | T
                | {
                    anchorId?: T;
                    spacingTop?: T;
                    spacingBottom?: T;
                  };
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              blockSettings?:
                | T
                | {
                    anchorId?: T;
                    spacingTop?: T;
                    spacingBottom?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              pricingItems?:
                | T
                | {
                    service?: T;
                    tierLabel?: T;
                    id?: T;
                  };
              blockSettings?:
                | T
                | {
                    anchorId?: T;
                    spacingTop?: T;
                    spacingBottom?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              testimonials?: T;
              blockSettings?:
                | T
                | {
                    anchorId?: T;
                    spacingTop?: T;
                    spacingBottom?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              showSocialIcons?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    link?: T;
                    variant?: T;
                    id?: T;
                  };
              blockSettings?:
                | T
                | {
                    anchorId?: T;
                    spacingTop?: T;
                    spacingBottom?: T;
                  };
              id?: T;
              blockName?: T;
            };
        promotion?:
          | T
          | {
              variant?: T;
              badge?: T;
              heading?: T;
              description?: T;
              price?: T;
              priceLabel?: T;
              originalPrice?: T;
              ctaLabel?: T;
              footnote?: T;
              blockSettings?:
                | T
                | {
                    anchorId?: T;
                    spacingTop?: T;
                    spacingBottom?: T;
                  };
              id?: T;
              blockName?: T;
            };
        location?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              grandOpeningLabel?: T;
              blockSettings?:
                | T
                | {
                    anchorId?: T;
                    spacingTop?: T;
                    spacingBottom?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  featuredImage?: T;
  excerpt?: T;
  authors?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  description?: T;
  longDescription?: T;
  icon?: T;
  features?:
    | T
    | {
        feature?: T;
        description?: T;
        id?: T;
      };
  startingPrice?: T;
  competitorPrice?: T;
  priceTiers?:
    | T
    | {
        label?: T;
        price?: T;
        competitorPrice?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorDescription?: T;
  authorInitials?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, hours, and booking link used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-info".
 */
export interface ClinicInfo {
  id: string;
  /**
   * Display format, e.g. "(520) 555-0123"
   */
  phone?: string | null;
  email?: string | null;
  /**
   * Link for the "Schedule Appointment" button
   */
  bookingUrl?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  socialMedia?: {
    facebook?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
  };
  hours?: {
    monday?: {
      closed?: boolean | null;
      /**
       * 24h format (e.g. 08:00)
       */
      open?: string | null;
      /**
       * 24h format (e.g. 18:00)
       */
      close?: string | null;
    };
    tuesday?: {
      closed?: boolean | null;
      /**
       * 24h format (e.g. 08:00)
       */
      open?: string | null;
      /**
       * 24h format (e.g. 18:00)
       */
      close?: string | null;
    };
    wednesday?: {
      closed?: boolean | null;
      /**
       * 24h format (e.g. 08:00)
       */
      open?: string | null;
      /**
       * 24h format (e.g. 18:00)
       */
      close?: string | null;
    };
    thursday?: {
      closed?: boolean | null;
      /**
       * 24h format (e.g. 08:00)
       */
      open?: string | null;
      /**
       * 24h format (e.g. 18:00)
       */
      close?: string | null;
    };
    friday?: {
      closed?: boolean | null;
      /**
       * 24h format (e.g. 08:00)
       */
      open?: string | null;
      /**
       * 24h format (e.g. 18:00)
       */
      close?: string | null;
    };
    saturday?: {
      closed?: boolean | null;
      /**
       * 24h format (e.g. 08:00)
       */
      open?: string | null;
      /**
       * 24h format (e.g. 18:00)
       */
      close?: string | null;
    };
    sunday?: {
      closed?: boolean | null;
      /**
       * 24h format (e.g. 08:00)
       */
      open?: string | null;
      /**
       * 24h format (e.g. 18:00)
       */
      close?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the main navigation menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  items?:
    | {
        label: string;
        /**
         * Relative path (e.g. "/#services") or full URL
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-info_select".
 */
export interface ClinicInfoSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  bookingUrl?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
      };
  hours?:
    | T
    | {
        monday?:
          | T
          | {
              closed?: T;
              open?: T;
              close?: T;
            };
        tuesday?:
          | T
          | {
              closed?: T;
              open?: T;
              close?: T;
            };
        wednesday?:
          | T
          | {
              closed?: T;
              open?: T;
              close?: T;
            };
        thursday?:
          | T
          | {
              closed?: T;
              open?: T;
              close?: T;
            };
        friday?:
          | T
          | {
              closed?: T;
              open?: T;
              close?: T;
            };
        saturday?:
          | T
          | {
              closed?: T;
              open?: T;
              close?: T;
            };
        sunday?:
          | T
          | {
              closed?: T;
              open?: T;
              close?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}